title: Hello, world! I'm Raul Castro Fernandez
description: > # this means to ignore newlines until "baseurl:"
  Economics of data, value of data, academic research, data sharing, data management, machine learning, data value, data markets, data pricing
permalink: ':title/'
#baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
#baseurl: "/blog" # the subpath of your site, e.g. /blog
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raulcastrofernandez.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Raul Castro Fernandez # add your name
author-img: ../../img/raul-small.jpeg # add your photo
about-author: Assistant professor in computer science at the University of Chicago # add description
social-twitter: @raulcfernandez # add your Twitter handle
#social-facebook: # add your Facebook handle
#social-github: artemsheludko # add your Github handle
social-linkedin: www.linkedin.com/in/raulcfernandez # add your Linkedin handle
social-email: raulcf@uchicago.edu # add your Email address

# Disqus
#discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
#paginate_path: "/page/:num"
paginate_path: "/blog/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
